services:
  iesa:
    tty: true
    container_name: iesa
    dns:
    - ${IP_DOMAIN}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    extra_hosts:
    - ${FQDN}:${IP_DOMAIN}
    volumes:
      - ./storage:/mnt/storage
      - ./logs/cid:/var/log/cid
      - ./logs/samba:/var/log/samba
    env_file:
      - .env
    command: >
      tail -f /var/log/cid/functions.log"