services:
  iesa:
    tty: true
    container_name: iesa
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./storage:/mnt/storage
      - ./logs/cid:/var/log/cid
      - ./logs/samba:/var/log/samba
      - ./docker/samba:/etc/samba
    ports:
      - 9001:80
    env_file:
      - .env